name: core
description: App core infrastructure.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.1.4
  fluttertoast: 8.0.9
  flutter_svg: ^1.1.6
  rxdart: ^0.27.7
  intl: ^0.17.0
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/seed_data/task_labels.json
    - assets/seed_data/task_states.json
    - assets/seed_data/tasks.json