name: task_management
description: Task management package handles task's CRUD.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../infrastructure/core
  navigator:
    path: ../../infrastructure/navigator
  dropdown_button2: ^1.9.2
  path_provider: ^2.0.11
  csv: ^5.0.1
  permission_handler: ^10.2.0
  share_plus: ^6.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/subtitles/
    - assets/icons/
